name: Continuous Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build solution
      run: dotnet build --configuration Release
      
    - name: Generate coverage report
      run: dotnet test --collect "XPlat Code Coverage" --results-directory "./test-results"